name = "dockycount"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyAjmXMMafuPYkYi1GzrnucNJSjxypN2gYQ"
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "docky-dev-fr.firebaseapp.com"
NEXT_PUBLIC_FIREBASE_PROJECT_ID = "docky-dev-fr"
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "docky-dev-fr.firebasestorage.app"
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "548202839817"
NEXT_PUBLIC_FIREBASE_APP_ID = "1:548202839817:web:832f713ae5135e41809dd8"
NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID = "G-KLXHVFYQYY"
